image: hirokimatsumoto/alpine-openjdk-11

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - package

build:
  stage: build
  script: ./gradlew build

package:
  stage: package
  script: ./gradlew bundlePlugin
