image: openjdk:12.0-jdk-oracle

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=true -Dorg.gradle.jvmargs=-Xmx2024m"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - package

build:
  stage: build
  script: ./gradlew integTestRunner --console=plain --profile
  artifacts:
    paths:
      - reports/profile/
    expire_in: 1 hours

package:
  stage: package
  script: ./gradlew bundlePlugin --console=plain --profile
