image: gradle:5.4.0-jre11-slim

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  
before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - package

build:
  stage: build
  script: ./gradlew build

package:
  stage: package
  script: ./gradlew bundlePlugin
