# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.12'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'bundlePlugin'
- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: 'build/distributions/**/?(*.zip)'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: fast-cosine-similarity-plugin.zip
- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: elasticsearch-fast-cosine-similarity:$(Build.BuildId)
- task: ECRPushImage@1
  inputs:
    awsCredentials: 'AWS DevelopmentPowerUser'
    regionName: 'eu-west-1'
    imageSource: 'imagename'
    sourceImageName: elasticsearch-fast-cosine-similarity
    sourceImageTag: $(Build.BuildId)
    repositoryName: 'search-squad/neil-andrassy'
    autoCreateRepository: true
    logRequest: true
    logResponse: true
